version: "3.9"

services:
  whatsapp-chatbot:
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data:/whatsapp-chatbot:rw
      - /usr/src/app/node_modules
