version: "3.9"

services:
  puppeteer-container:
    image: ghcr.io/puppeteer/puppeteer
    cap_add:
      - SYS_ADMIN
    ports:
      - 4000:4000

  whatsapp-chatbot:
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PUPPETEER_WS_ENDPOINT=puppeteer-container:4000  # Set the Puppeteer WebSocket endpoint
    depends_on:
      - puppeteer-container
    volumes:
      - ./data:/whatsapp-chatbot:rw
      - /usr/src/app/node_modules
