version: "3.9"

services:
  flowise:
    build:
      context: ./
      dockerfile: flowise.Dockerfile
    image: flowiseai/flowise
    restart: always
    env_file:
      - .env.flowise
    ports:
      - 3000:3000
    volumes:
      - flowise_fileshare:~/.flowise:/root/.flowise
    command: /bin/sh -c "sleep 3; flowise start"

  whatsapp-chatbot:
    build: ./
    restart: unless-stopped
    ports:
      - 6543:6543
    cap_add:
      - SYS_ADMIN
    volumes:
      - chatsapp_fileshare:.:/whatsapp-chatbot:rw

volumes:
  flowise_fileshare:
    driver: azure_file
    driver_opts:
      share_name: sqlite-flowise
      storage_account_name: flowisepersistent

  chatsapp_fileshare:
    driver: azure_file
    driver_opts:
      share_name: sqlbackend
      storage_account_name: flowisepersistent
